<a href="https://colab.research.google.com/github/rvidals/Analise_Exploratoria_Concatenacao_Pop_Resid_CGIAE/blob/main/Analise_Exploratoria_Concatena%C3%A7%C3%A3o_Pop_Resid_CGIAE_Atualizado_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Código para concatenar vários csv e ordenar a partir do Sexo e o código do Município

In [ ]:
#Importando a biblioteca pandas
import pandas as pd
from google.colab import files

In [ ]:
#Importar os arquivos csv e salvando na variável pop

pop = files.upload()

Saving A142526189_28_143_208_SINASC_2020.csv to A142526189_28_143_208_SINASC_2020.csv
Saving A130125189_28_143_208.csv to A130125189_28_143_208.csv
Saving A130059189_28_143_208.csv to A130059189_28_143_208.csv
Saving A130004189_28_143_208.csv to A130004189_28_143_208.csv
Saving A125925189_28_143_208.csv to A125925189_28_143_208.csv
Saving A125847189_28_143_208.csv to A125847189_28_143_208.csv
Saving A125757189_28_143_208.csv to A125757189_28_143_208.csv
Saving A125555189_28_143_208.csv to A125555189_28_143_208.csv
Saving A125518189_28_143_208.csv to A125518189_28_143_208.csv
Saving A125331189_28_143_208.csv to A125331189_28_143_208.csv
Saving A125250189_28_143_208.csv to A125250189_28_143_208.csv
Saving A125132189_28_143_208.csv to A125132189_28_143_208.csv
Saving A124945189_28_143_208.csv to A124945189_28_143_208.csv
Saving A101443189_28_143_208.csv to A101443189_28_143_208.csv
Saving A101404189_28_143_208.csv to A101404189_28_143_208.csv
Saving A101349189_28_143_208.csv to A101349189_28_143_208.csv
Saving A101340189_28_143_208.csv to A101340189_28_143_208.csv
Saving A101331189_28_143_208.csv to A101331189_28_143_208.csv
Saving A101251189_28_143_208.csv to A101251189_28_143_208.csv
Saving A101239189_28_143_208.csv to A101239189_28_143_208.csv
Saving A101224189_28_143_208.csv to A101224189_28_143_208.csv
Saving A101201189_28_143_208.csv to A101201189_28_143_208.csv
Saving A101151189_28_143_208.csv to A101151189_28_143_208.csv
Saving A101137189_28_143_208.csv to A101137189_28_143_208.csv
Saving A100952189_28_143_208.csv to A100952189_28_143_208.csv
Saving A100943189_28_143_208.csv to A100943189_28_143_208.csv
Saving A100932189_28_143_208.csv to A100932189_28_143_208.csv
Saving A100916189_28_143_208.csv to A100916189_28_143_208.csv
Saving A100847189_28_143_208.csv to A100847189_28_143_208.csv
Saving A100834189_28_143_208.csv to A100834189_28_143_208.csv
Saving A100810189_28_143_208.csv to A100810189_28_143_208.csv
Saving A100800189_28_143_208.csv to A100800189_28_143_208.csv
Saving A100752189_28_143_208.csv to A100752189_28_143_208.csv
Saving A100722189_28_143_208.csv to A100722189_28_143_208.csv
Saving A100711189_28_143_208.csv to A100711189_28_143_208.csv
Saving A100700189_28_143_208.csv to A100700189_28_143_208.csv
Saving A100649189_28_143_208.csv to A100649189_28_143_208.csv
Saving A100638189_28_143_208.csv to A100638189_28_143_208.csv
Saving A100627189_28_143_208.csv to A100627189_28_143_208.csv
Saving A100604189_28_143_208.csv to A100604189_28_143_208.csv
Saving A100548189_28_143_208.csv to A100548189_28_143_208.csv
Saving A100539189_28_143_208.csv to A100539189_28_143_208.csv
Saving A100528189_28_143_208.csv to A100528189_28_143_208.csv
Saving A100517189_28_143_208.csv to A100517189_28_143_208.csv
Saving A100506189_28_143_208.csv to A100506189_28_143_208.csv
Saving A100434189_28_143_208.csv to A100434189_28_143_208.csv
Saving A100423189_28_143_208.csv to A100423189_28_143_208.csv
Saving A100005189_28_143_208.csv to A100005189_28_143_208.csv
Saving A095953189_28_143_208.csv to A095953189_28_143_208.csv
Saving A095931189_28_143_208.csv to A095931189_28_143_208.csv
Saving A095918189_28_143_208.csv to A095918189_28_143_208.csv
Saving A095907189_28_143_208.csv to A095907189_28_143_208.csv
Saving A095845189_28_143_208.csv to A095845189_28_143_208.csv
Saving A095825189_28_143_208.csv to A095825189_28_143_208.csv
Saving A095802189_28_143_208.csv to A095802189_28_143_208.csv
Saving A095746189_28_143_208.csv to A095746189_28_143_208.csv
Saving A095725189_28_143_208.csv to A095725189_28_143_208.csv
Saving A095715189_28_143_208.csv to A095715189_28_143_208.csv
Saving A095705189_28_143_208.csv to A095705189_28_143_208.csv
Saving A095654189_28_143_208.csv to A095654189_28_143_208.csv
Saving A095626189_28_143_208.csv to A095626189_28_143_208.csv
Saving A095614189_28_143_208.csv to A095614189_28_143_208.csv
Saving A095602189_28_143_208.csv to A095602189_28_143_208.csv
Saving A095548189_28_143_208.csv to A095548189_28_143_208.csv
Saving A095534189_28_143_208.csv to A095534189_28_143_208.csv
Saving A095501189_28_143_208.csv to A095501189_28_143_208.csv
Saving A095437189_28_143_208.csv to A095437189_28_143_208.csv
Saving A095427189_28_143_208.csv to A095427189_28_143_208.csv
Saving A095416189_28_143_208.csv to A095416189_28_143_208.csv
Saving A095406189_28_143_208.csv to A095406189_28_143_208.csv
Saving A095358189_28_143_208.csv to A095358189_28_143_208.csv
Saving A095346189_28_143_208.csv to A095346189_28_143_208.csv
Saving A095319189_28_143_208.csv to A095319189_28_143_208.csv
Saving A095310189_28_143_208.csv to A095310189_28_143_208.csv
Saving A095258189_28_143_208.csv to A095258189_28_143_208.csv
Saving A095227189_28_143_208.csv to A095227189_28_143_208.csv
Saving A095204189_28_143_208.csv to A095204189_28_143_208.csv
Saving A095146189_28_143_208.csv to A095146189_28_143_208.csv
Saving A095116189_28_143_208.csv to A095116189_28_143_208.csv
Saving A095101189_28_143_208.csv to A095101189_28_143_208.csv
Saving A094428189_28_143_208.csv to A094428189_28_143_208.csv

In [ ]:
#Caminho onde serão salvo os arquivos
path = '/content/'

In [ ]:
li_M = [] # os valores são atribuidos à uma lista
li_F = [] # os valores são atribuidos à uma lista


# o método key foi usado para chamar os  nomes dos arquivos presentes no google colab
for name in pop.keys():

  #Essa parte é para pegar a faixa etária e renomear a coluna sexo
  df_fEtaria  = pd.read_csv(path+name, encoding='latin1', header=None)
  # fEtaria = df_fEtaria.iat[3,0]
  fEtaria = df_fEtaria.iat[2,0].replace(';','')
  print(fEtaria)
  fEtaria = fEtaria.split(':')[1].replace('  ',' ').replace(' ','_')
  
  #print(name,': ',fEtaria) #visualizar a execução da extração

  #Essa parte é para pegar o csv que gerará a nava tabela
  # o csv vem com informações além das tabulaeres 
  # Para fazer essa limpeza foi utilizados as flegues skiprows, skipfooter e header
  df = pd.read_csv(path+name, skiprows=2, encoding='latin1', header=2, sep=';')
  df2 = df.rename(columns={"Masculino": "Masculino"+fEtaria, "Feminino": "Feminino"+fEtaria})
  
  #Lista onde será salvo as colunas da tabela para concatenar 
  li_M.append(df2["Masculino"+fEtaria]) # atribuindo as colunas renomeadas à lista
  li_F.append(df2["Feminino"+fEtaria]) # atribuindo as colunas renomeadas à lista

In [ ]:
li_IBGE = [] # o Código do IBGE e nome do município será atribuido a esta lista

li_IBGE.append(df["Município"].str.split(' ',
                                         1,
                                         expand=True).rename(columns = {0: 'COD_MUN',
                                                                       1:'NM_MUN'})) 

#Estou inserindo os dados do ibge na lista masculina
li_IBGE_M = li_IBGE + li_M 
#Estou inserindo os dados do ibge na lista masculina
li_IBGE_F = li_IBGE + li_F

#Concatenando os valores em um DataFrame
concat_M = pd.concat(li_IBGE_M , axis=1) # concatenando pelo eixo y = 1
concat_F = pd.concat(li_IBGE_F, axis=1) #Vizualização

In [ ]:
#Inserção da coluna Sexo: M e F
concat_M.insert(2,'Sexo','M')
concat_F.insert(2,'Sexo','F')

#Renomeando as colunas 

"""Foi feito um print na estrutura de renomeação utilizando os métodos
.columns.values"""

concat_M = concat_M.rename(columns={'COD_MUN': 'COD_MUN',
'NM_MUN': 'NM_MUN',
'Sexo': 'Sexo',
'Masculino_1_ano': '1_ano',
'Masculino_2_anos': '2_anos',
'Masculino_3_anos': '3_anos',
'Masculino_4_anos': '4_anos',
'Masculino_5_anos': '5_anos',
'Masculino_6_anos': '6_anos',
'Masculino_7_anos': '7_anos',
'Masculino_8_anos': '8_anos',
'Masculino_9_anos': '9_anos',
'Masculino_10_anos': '10_anos',
'Masculino_11_anos': '11_anos',
'Masculino_12_anos': '12_anos',
'Masculino_13_anos': '13_anos',
'Masculino_14_anos': '14_anos',
'Masculino_15_anos': '15_anos',
'Masculino_16_anos': '16_anos',
'Masculino_17_anos': '17_anos',
'Masculino_18_anos': '18_anos',
'Masculino_19_anos': '19_anos',
'Masculino_20_anos': '20_anos',
'Masculino_21_anos': '21_anos',
'Masculino_22_anos': '22_anos',
'Masculino_23_anos': '23_anos',
'Masculino_24_anos': '24_anos',
'Masculino_25_anos': '25_anos',
'Masculino_26_anos': '26_anos',
'Masculino_27_anos': '27_anos',
'Masculino_28_anos': '28_anos',
'Masculino_29_anos': '29_anos',
'Masculino_30_anos': '30_anos',
'Masculino_31_anos': '31_anos',
'Masculino_32_anos': '32_anos',
'Masculino_33_anos': '33_anos',
'Masculino_34_anos': '34_anos',
'Masculino_35_anos': '35_anos',
'Masculino_36_anos': '36_anos',
'Masculino_37_anos': '37_anos',
'Masculino_38_anos': '38_anos',
'Masculino_39_anos': '39_anos',
'Masculino_40_anos': '40_anos',
'Masculino_41_anos': '41_anos',
'Masculino_42_anos': '42_anos',
'Masculino_43_anos': '43_anos',
'Masculino_44_anos': '44_anos',
'Masculino_45_anos': '45_anos',
'Masculino_46_anos': '46_anos',
'Masculino_47_anos': '47_anos',
'Masculino_48_anos': '48_anos',
'Masculino_49_anos': '49_anos',
'Masculino_50_anos': '50_anos',
'Masculino_51_anos': '51_anos',
'Masculino_52_anos': '52_anos',
'Masculino_53_anos': '53_anos',
'Masculino_54_anos': '54_anos',
'Masculino_55_anos': '55_anos',
'Masculino_56_anos': '56_anos',
'Masculino_57_anos': '57_anos',
'Masculino_58_anos': '58_anos',
'Masculino_59_anos': '59_anos',
'Masculino_60_anos': '60_anos',
'Masculino_61_anos': '61_anos',
'Masculino_62_anos': '62_anos',
'Masculino_63_anos': '63_anos',
'Masculino_64_anos': '64_anos',
'Masculino_65_anos': '65_anos',
'Masculino_66_anos': '66_anos',
'Masculino_67_anos': '67_anos',
'Masculino_68_anos': '68_anos',
'Masculino_69_anos': '69_anos',
'Masculino_70_anos': '70_anos',
'Masculino_71_anos': '71_anos',
'Masculino_72_anos': '72_anos',
'Masculino_73_anos': '73_anos',
'Masculino_74_anos': '74_anos',
'Masculino_75_anos': '75_anos',
'Masculino_76_anos': '76_anos',
'Masculino_77_anos': '77_anos',
'Masculino_78_anos': '78_anos',
'Masculino_79_anos': '79_anos',
'Masculino_80_anos_e_mais': '80_anos_e_mais',
'Masculino_Menos_que_1_ano_de_idade': 'Menos_que_1_ano_de_idade'
})

concat_F = concat_F.rename(columns={'COD_MUN': 'COD_MUN',
'NM_MUN': 'NM_MUN',
'Sexo': 'Sexo',
'Feminino_1_ano': '1_ano',
'Feminino_2_anos': '2_anos',
'Feminino_3_anos': '3_anos',
'Feminino_4_anos': '4_anos',
'Feminino_5_anos': '5_anos',
'Feminino_6_anos': '6_anos',
'Feminino_7_anos': '7_anos',
'Feminino_8_anos': '8_anos',
'Feminino_9_anos': '9_anos',
'Feminino_10_anos': '10_anos',
'Feminino_11_anos': '11_anos',
'Feminino_12_anos': '12_anos',
'Feminino_13_anos': '13_anos',
'Feminino_14_anos': '14_anos',
'Feminino_15_anos': '15_anos',
'Feminino_16_anos': '16_anos',
'Feminino_17_anos': '17_anos',
'Feminino_18_anos': '18_anos',
'Feminino_19_anos': '19_anos',
'Feminino_20_anos': '20_anos',
'Feminino_21_anos': '21_anos',
'Feminino_22_anos': '22_anos',
'Feminino_23_anos': '23_anos',
'Feminino_24_anos': '24_anos',
'Feminino_25_anos': '25_anos',
'Feminino_26_anos': '26_anos',
'Feminino_27_anos': '27_anos',
'Feminino_28_anos': '28_anos',
'Feminino_29_anos': '29_anos',
'Feminino_30_anos': '30_anos',
'Feminino_31_anos': '31_anos',
'Feminino_32_anos': '32_anos',
'Feminino_33_anos': '33_anos',
'Feminino_34_anos': '34_anos',
'Feminino_35_anos': '35_anos',
'Feminino_36_anos': '36_anos',
'Feminino_37_anos': '37_anos',
'Feminino_38_anos': '38_anos',
'Feminino_39_anos': '39_anos',
'Feminino_40_anos': '40_anos',
'Feminino_41_anos': '41_anos',
'Feminino_42_anos': '42_anos',
'Feminino_43_anos': '43_anos',
'Feminino_44_anos': '44_anos',
'Feminino_45_anos': '45_anos',
'Feminino_46_anos': '46_anos',
'Feminino_47_anos': '47_anos',
'Feminino_48_anos': '48_anos',
'Feminino_49_anos': '49_anos',
'Feminino_50_anos': '50_anos',
'Feminino_51_anos': '51_anos',
'Feminino_52_anos': '52_anos',
'Feminino_53_anos': '53_anos',
'Feminino_54_anos': '54_anos',
'Feminino_55_anos': '55_anos',
'Feminino_56_anos': '56_anos',
'Feminino_57_anos': '57_anos',
'Feminino_58_anos': '58_anos',
'Feminino_59_anos': '59_anos',
'Feminino_60_anos': '60_anos',
'Feminino_61_anos': '61_anos',
'Feminino_62_anos': '62_anos',
'Feminino_63_anos': '63_anos',
'Feminino_64_anos': '64_anos',
'Feminino_65_anos': '65_anos',
'Feminino_66_anos': '66_anos',
'Feminino_67_anos': '67_anos',
'Feminino_68_anos': '68_anos',
'Feminino_69_anos': '69_anos',
'Feminino_70_anos': '70_anos',
'Feminino_71_anos': '71_anos',
'Feminino_72_anos': '72_anos',
'Feminino_73_anos': '73_anos',
'Feminino_74_anos': '74_anos',
'Feminino_75_anos': '75_anos',
'Feminino_76_anos': '76_anos',
'Feminino_77_anos': '77_anos',
'Feminino_78_anos': '78_anos',
'Feminino_79_anos': '79_anos',
'Feminino_80_anos_e_mais': '80_anos_e_mais',
'Feminino_Menos_que_1_ano_de_idade': 'Menos_que_1_ano_de_idade'})

#Concatenando as colunas Masculino e Feminino
popConcat = pd.concat([concat_M,concat_F])

In [ ]:
popConcat

,COD_MUN,NM_MUN,Sexo,Menos_que_1_ano_de_idade,76_anos,75_anos,71_anos,61_anos,57_anos,56_anos,...,14_anos,12_anos,11_anos,10_anos,8_anos,7_anos,6_anos,4_anos,3_anos,2_anos
0,110001,Alta Floresta D'Oeste,M,174.0,35.0,39.0,53.0,121.0,151.0,153.0,...,162.0,161.0,160.0,158.0,163.0,166.0,169.0,164.0,167.0,165.0
1,110037,Alto Alegre dos Parecis,M,70.0,19.0,20.0,28.0,55.0,79.0,83.0,...,101.0,99.0,100.0,100.0,106.0,109.0,113.0,113.0,116.0,115.0
2,110040,Alto Paraíso,M,113.0,29.0,31.0,43.0,99.0,122.0,127.0,...,167.0,164.0,165.0,169.0,185.0,192.0,197.0,193.0,199.0,197.0
3,110034,Alvorada D'Oeste,M,115.0,22.0,24.0,35.0,75.0,84.0,87.0,...,97.0,96.0,96.0,96.0,99.0,102.0,104.0,102.0,104.0,104.0
4,110002,Ariquemes,M,739.0,121.0,135.0,200.0,432.0,524.0,549.0,...,867.0,824.0,813.0,810.0,827.0,845.0,862.0,851.0,867.0,863.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5568,522230,Vila Propício,F,24.0,12.0,13.0,19.0,26.0,39.0,41.0,...,32.0,31.0,32.0,34.0,38.0,40.0,42.0,42.0,43.0,42.0
5569,530010,Brasília,F,19217.0,5334.0,5893.0,8115.0,14342.0,17303.0,17899.0,...,21277.0,19516.0,18728.0,18263.0,18190.0,18815.0,19246.0,18879.0,19781.0,20213.0
5570,Total,None,F,1331658.0,466394.0,506911.0,667008.0,1076713.0,1215937.0,1240632.0,...,1455779.0,1433959.0,1412946.0,1416129.0,1417555.0,1436481.0,1465004.0,1425478.0,1450150.0,1442881.0
5571,,Fonte:,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5572,,2000 a 2021  Estimativas preliminares elabora...,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Criar cópia 

popConcat_copy = popConcat.copy()
#Ordenando as colunas. 
popConcat_copy = popConcat_copy[['COD_MUN','NM_MUN','Sexo','Menos_que_1_ano_de_idade',
                       '1_ano','2_anos','3_anos','4_anos','5_anos','6_anos',
                       '7_anos','8_anos','9_anos','10_anos','11_anos',
                       '12_anos','13_anos','14_anos','15_anos','16_anos',
                       '17_anos','18_anos','19_anos','20_anos','21_anos',
                       '22_anos','23_anos','24_anos','25_anos','26_anos',
                       '27_anos','28_anos','29_anos','30_anos','31_anos',
                       '32_anos','33_anos','34_anos','35_anos','36_anos',
                       '37_anos','38_anos','39_anos','40_anos','41_anos',
                       '42_anos','43_anos','44_anos','45_anos','46_anos',
                       '47_anos','48_anos','49_anos','50_anos','51_anos',
                       '52_anos','53_anos','54_anos','55_anos','56_anos',
                       '57_anos','58_anos','59_anos','60_anos','61_anos',
                       '62_anos','63_anos','64_anos','65_anos','66_anos',
                       '67_anos','68_anos','69_anos','70_anos','71_anos',
                       '72_anos','73_anos','74_anos','75_anos','76_anos',
                       '77_anos','78_anos','79_anos','80_anos_e_mais']]

#Ordenando as linhas a partir das colunas COD_MUN e Sexo e resetando o index
popResid = popConcat_copy.sort_values(['COD_MUN','Sexo']).reset_index(drop=True)

#O quantitativo populacional de 1 ano é o mesmo do Menos_que_1_ano_de_idade
popResid['1_ano'] = popResid['Menos_que_1_ano_de_idade']

#Excluindo os valores no início que não serão usados
popResid = popResid.drop(range(0,4))#.reset_index(drop=True)

#Excluindo os valores do fim que não serão usados
popResid = popResid.drop(range(11144,11146)).reset_index(drop=True)

#Salvando o arquivo final em XLSX
popResid.to_excel('Populacao_Residente_Brasil_SUS.xlsx')

#Visualizando o resultado final
popResid

,COD_MUN,NM_MUN,Sexo,Menos_que_1_ano_de_idade,1_ano,2_anos,3_anos,4_anos,5_anos,6_anos,...,71_anos,72_anos,73_anos,74_anos,75_anos,76_anos,77_anos,78_anos,79_anos,80_anos_e_mais
0,110001,Alta Floresta D'Oeste,F,159.0,159.0,157.0,159.0,155.0,154.0,158.0,...,50.0,45.0,42.0,39.0,36.0,34.0,32.0,31.0,30,153.0
1,110001,Alta Floresta D'Oeste,M,174.0,174.0,165.0,167.0,164.0,164.0,169.0,...,53.0,48.0,45.0,42.0,39.0,35.0,33.0,32.0,32,175.0
2,110002,Ariquemes,F,768.0,768.0,821.0,827.0,815.0,810.0,830.0,...,206.0,186.0,169.0,154.0,140.0,128.0,116.0,105.0,94,555.0
3,110002,Ariquemes,M,739.0,739.0,863.0,867.0,851.0,843.0,862.0,...,200.0,183.0,166.0,151.0,135.0,121.0,108.0,96.0,86,551.0
4,110003,Cabixi,F,31.0,31.0,37.0,37.0,37.0,36.0,36.0,...,13.0,11.0,10.0,9.0,8.0,7.0,7.0,6.0,6,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11135,522220,Vila Boa,M,26.0,26.0,59.0,59.0,57.0,57.0,58.0,...,9.0,8.0,8.0,7.0,6.0,6.0,6.0,5.0,5,24.0
11136,522230,Vila Propício,F,24.0,24.0,42.0,43.0,42.0,41.0,42.0,...,19.0,17.0,16.0,14.0,13.0,12.0,10.0,9.0,8,51.0
11137,522230,Vila Propício,M,29.0,29.0,46.0,47.0,45.0,46.0,48.0,...,17.0,16.0,15.0,14.0,13.0,11.0,10.0,10.0,9,41.0
11138,530010,Brasília,F,19217.0,19217.0,20213.0,19781.0,18879.0,18790.0,19246.0,...,8115.0,7568.0,7023.0,6474.0,5893.0,5334.0,4817.0,4371.0,4044,28485.0
11139,530010,Brasília,M,20139.0,20139.0,21273.0,20849.0,19936.0,19854.0,20325.0,...,5890.0,5405.0,4948.0,4513.0,4076.0,3645.0,3250.0,2923.0,2676,16543.0

In [ ]:
popResid.shape

(11144, 84)

In [ ]:
#Linha de comando 
#Excluir todos os csv

#!rm *.csv

In [ ]:
#Linha de comando 
#Listar o que está na pasta PopSUS

#!ls PopSUS/ #Tirar o comentário para usar!

In [ ]:
#Linha de comando
#Compactando os csv

#!zip -r /content/PopSUS.zip /content/PopSUS/* #Tirar o comentário para usar!

# LOOP para polpar tempo e  para criar a lista a ser renomeada

In [ ]:
for colM in concat_M.columns.values:
  rname = colM.split('Masculino_')[-1]
  print(f"'{colM}': '{rname}',")

In [ ]:
for colF in concat_F.columns.values:
  rname = colF.split('Feminino_')[-1]
  print(f"'{colF}': '{rname}',")

# Estruturas de loop não funcionais porém, a lógica aplicada pode ser utilizada em aplicações futuras!

In [ ]:
#Não está funcionando, porém é um exemplo de loop

codIBGE_nmMuni = df['Município'].str.split(' ', 1)
count = 0
cod_ibge = []
nm_mun = []
while count <= len(codIBGE_nmMuni): 
  #print(count)
  c = codIBGE_nmMuni[count][1]
  cod_ibge.append(c)
  n =  codIBGE_nmMuni[count][0]
  nm_mun.append(n)
  count += 1

In [ ]:
#Não está funcionando, porém é um exemplo de loop
codIBGE_nmMuni = df['Município'].str.split(' ', 1)
x = 0
cod_ibge = []
nm_mun = []
for codigos in range(len(codIBGE_nmMuni)):

  c = codigos[x][1]
  cod_ibge.append(c)
  n =  codigos[x][0]
  nm_mun.append(n)
  x += 1